// Code generated by go2go; DO NOT EDIT.


//line doc.go2:55
package rangeset

//line doc.go2:55
import (
//line doc.go2:55
 "alg"
//line doc.go2:55
 "constraints"
//line doc.go2:55
 "context"
//line doc.go2:55
 "fmt"
//line doc.go2:55
 "math"
//line doc.go2:55
 "slices"
//line doc.go2:55
 "strconv"
//line doc.go2:55
 "strings"
//line doc.go2:55
 "testing"
//line doc.go2:55
)

//line doc.go2:55
type _ alg.Importable୦
//line doc.go2:55
type _ constraints.Importable୦

//line doc.go2:55
var _ = context.Background
//line doc.go2:55
var _ = fmt.Errorf
//line doc.go2:55
var _ = math.Abs

//line doc.go2:55
type _ slices.Importable୦

//line doc.go2:55
var _ = strconv.AppendBool

//line doc.go2:55
type _ strings.Builder

//line doc.go2:55
var _ = testing.AllocsPerRun
